apiVersion: v1
kind: Service
metadata:
  name: redis-np
  namespace: redis
spec:
  type: NodePort
  selector:
    app.kubernetes.io/component: master
    app.kubernetes.io/instance: redis
    app.kubernetes.io/name: redis
  ports:
    - name: tcp-redis
      protocol: TCP
      port: 6379
      targetPort: redis
      nodePort: 31679   # กำหนด NodePort (ช่วง 30000-32767)
